server:
  port: 10001
spring:
  application:
    name: tact-goods
  kafka:
    bootstrap-servers: ${KAFKA:192.168.1.253:9092}
  redis:
    host: ${REDIS:192.168.1.253}

topic:
  goods:
    event: ${GOODS_EVENT:goods_event}