server:
  port: 10002
spring:
  application:
    name: tact-order
  kafka:
    bootstrap-servers: ${KAFKA:192.168.1.253:9092}
  redis:
    host: ${REDIS:192.168.1.253}
topic:
  order:
    event: ${ORDER_EVENT:order_event}
    command: ${ORDER_COMMAND:order_command}
    callback: ${GOODS_COMMAND_CALLBACK:order_command_callback}